import 'package:flutter/material.dart';

List<String> videoExtensions = [
  ".3gp",
  ".asf",
  ".avi",
  ".m4u",
  ".m4v",
  ".mov",
  ".mp4",
  ".mpe",
  ".mpeg",
  ".mpg",
  ".mpg4",
  ".rmvb",
  ".wmv"
];
Map audioTypes = {
  ".m3u": "audio/x-mpegurl",
  ".m4a": "audio/mp4a-latm",
  ".m4b": "audio/mp4a-latm",
  ".m4p": "audio/mp4a-latm",
  ".wav": "audio/x-wav",
  ".wma": "audio/x-ms-wma",
  ".wmv": "audio/x-ms-wmv",
  ".rmvb": "audio/x-pn-realaudio",
  ".ogg": "audio/ogg",
  ".mpga": "audio/mpeg",
  ".mp2": "audio/x-mpeg",
  ".mp3": "audio/x-mpeg",
};
Map<String, IconData> fileIconMap = {
  ".3gp": Icons.videocam,
  ".torrent": Icons.cloud_download,
  ".kml": Icons.map,
  ".gpx": Icons.map,
  ".csv": Icons.table_chart,
  ".apk": Icons.android,
  ".asf": Icons.videocam,
  ".avi": Icons.videocam,
  ".bin": Icons.insert_drive_file,
  ".bmp": Icons.image,
  ".c": Icons.code,
  ".class": Icons.insert_drive_file,
  ".conf": Icons.text_snippet,
  ".cpp": Icons.code,
  ".doc": Icons.description,
  ".docx": Icons.description,
  ".xls": Icons.table_chart,
  ".xlsx": Icons.table_chart,
  ".exe": Icons.memory,
  ".gif": Icons.image,
  ".gtar": Icons.archive,
  ".gz": Icons.archive,
  ".h": Icons.code,
  ".htm": Icons.html,
  ".html": Icons.html,
  ".jar": Icons.archive,
  ".java": Icons.code,
  ".jpeg": Icons.image,
  ".jpg": Icons.image,
  ".js": Icons.code,
  ".log": Icons.text_snippet,
  ".m3u": Icons.music_note,
  ".m4a": Icons.audiotrack,
  ".m4b": Icons.audiotrack,
  ".m4p": Icons.audiotrack,
  ".m4u": Icons.videocam,
  ".m4v": Icons.videocam,
  ".mov": Icons.movie,
  ".mp2": Icons.audiotrack,
  ".mp3": Icons.audiotrack,
  ".mp4": Icons.movie,
  ".mpc": Icons.verified_user,
  ".mpe": Icons.movie,
  ".mpeg": Icons.movie,
  ".mpg": Icons.movie,
  ".mpg4": Icons.movie,
  ".mpga": Icons.audiotrack,
  ".msg": Icons.mail,
  ".ogg": Icons.audiotrack,
  ".pdf": Icons.picture_as_pdf,
  ".png": Icons.image,
  ".pps": Icons.slideshow,
  ".ppt": Icons.slideshow,
  ".pptx": Icons.slideshow,
  ".prop": Icons.text_snippet,
  ".rc": Icons.text_snippet,
  ".rmvb": Icons.videocam,
  ".rtf": Icons.text_snippet,
  ".sh": Icons.code,
  ".tar": Icons.archive,
  ".tgz": Icons.archive,
  ".txt": Icons.text_snippet,
  ".wav": Icons.audiotrack,
  ".wma": Icons.audiotrack,
  ".wmv": Icons.videocam,
  ".wps": Icons.description,
  ".xml": Icons.code,
  ".z": Icons.archive,
  ".zip": Icons.archive,
  "": Icons.insert_drive_file,
};

IconData getFileIcon(String extension) {
  return fileIconMap[extension] ?? Icons.insert_drive_file;
}

bool isVideoFile(String fileExtension) {
  return videoExtensions.contains(fileExtension);
}
